# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65ecb2a0c6c26c7cc4b05fbc32d4c040591d933db3c369abf9b2ad60736181c0f2b26b6bf115ba34e8535b5683c5427b54f591711753db42bbf497b153a5be8b

test:
  secret_key_base: a48fdb3affa8099375e70565db7d512a290fb7bb30476930d5180e1318ea4430ff60aa84b565b06a1dd6be2bd888793038b356a9225e7d04ea5e5d7e3fce77d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
